apiVersion: v1
kind: Service
metadata:
  name: cloudscale-final-service
spec:
  type: LoadBalancer
  selector:
    app: cloudscale-final-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
